// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:3.0.0.0
//      SpecFlow Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace VeevaCRM.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.0.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [TechTalk.SpecRun.FeatureAttribute("Veeva CRM Account Page Feature", SourceFile="Features\\Accounts.feature", SourceLine=0)]
    public partial class VeevaCRMAccountPageFeatureFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "Accounts.feature"
#line hidden
        
        [TechTalk.SpecRun.FeatureInitialize()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Veeva CRM Account Page Feature", null, ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [TechTalk.SpecRun.FeatureCleanup()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public virtual void TestInitialize()
        {
        }
        
        [TechTalk.SpecRun.ScenarioCleanup()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
        }
        
        public virtual void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Checking the the Accounts page", new string[] {
                "SmokeTest"}, SourceLine=3)]
        public virtual void CheckingTheTheAccountsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Checking the the Accounts page", null, new string[] {
                        "SmokeTest"});
#line 4
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 5
testRunner.Given("user opens browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 6
testRunner.Then("user entered into the application by using valid login credentials", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 7
testRunner.And("user is on home page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 8
testRunner.Then("Check if call is associated with the user or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 9
testRunner.Then("user clicks on my Accounts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 10
testRunner.And("verifies the Title of the Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Checking the the veiw drop down in Accounts page", new string[] {
                "SmokeTest"}, SourceLine=12)]
        public virtual void CheckingTheTheVeiwDropDownInAccountsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Checking the the veiw drop down in Accounts page", null, new string[] {
                        "SmokeTest"});
#line 13
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 14
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 15
testRunner.Then("Check the view Drop down values against Requirement", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for commercial channel", new string[] {
                "SmokeTest"}, SourceLine=17)]
        public virtual void CheckingTheDataForCommercialChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for commercial channel", null, new string[] {
                        "SmokeTest"});
#line 18
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 19
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 20
testRunner.When("view selected is commercial", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 21
testRunner.And("click on one commercial plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 22
testRunner.Then("Check the Header", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 23
testRunner.And("check the selected items in the particular Account", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for Account Detail for commercial view", new string[] {
                "SmokeTest"}, SourceLine=25)]
        public virtual void CheckTheDataForAccountDetailForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for Account Detail for commercial view", null, new string[] {
                        "SmokeTest"});
#line 26
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 27
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 28
testRunner.Then("check the items in Account Detail", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check weather the Account Details name is same as AccountName or not  for commerc" +
            "ial view", new string[] {
                "SmokeTest"}, SourceLine=30)]
        public virtual void CheckWeatherTheAccountDetailsNameIsSameAsAccountNameOrNotForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check weather the Account Details name is same as AccountName or not  for commerc" +
                    "ial view", null, new string[] {
                        "SmokeTest"});
#line 31
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 32
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 33
testRunner.Then("compare the accountname with the account Details", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check Formulary for commercial view", new string[] {
                "SmokeTest"}, SourceLine=35)]
        public virtual void CheckFormularyForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check Formulary for commercial view", null, new string[] {
                        "SmokeTest"});
#line 36
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 37
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 38
testRunner.Then("check the items in Formulary", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Coverage Policy items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=40)]
        public virtual void CheckTheCoveragePolicyItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Coverage Policy items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 41
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 42
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 43
testRunner.Then("check the items in CovergePolicy", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the pharmacy Services items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=45)]
        public virtual void CheckThePharmacyServicesItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the pharmacy Services items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 46
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 47
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 48
testRunner.Then("check the items in pharmacy Services", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Plan Products items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=50)]
        public virtual void CheckThePlanProductsItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Plan Products items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 51
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 52
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 53
testRunner.Then("check the items in Plan Products", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Specialty Providers items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=55)]
        public virtual void CheckTheSpecialtyProvidersItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Specialty Providers items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 56
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 57
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 58
testRunner.Then("check the items in Specialty Providers", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the (Member Of) of items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=60)]
        public virtual void CheckTheMemberOfOfItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the (Member Of) of items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 61
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 62
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 63
testRunner.Then("check the items in Member Of", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Member items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=65)]
        public virtual void CheckTheMemberItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Member items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 66
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 67
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 68
testRunner.Then("check the items in Member", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Address items for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=70)]
        public virtual void CheckTheAddressItemsForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Address items for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 71
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 72
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 73
testRunner.Then("check the items in Address", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Account Plan for Commercial View", new string[] {
                "SmokeTest"}, SourceLine=75)]
        public virtual void CheckTheAccountPlanForCommercialView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Account Plan for Commercial View", null, new string[] {
                        "SmokeTest"});
#line 76
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 77
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 78
testRunner.Then("check the items in Account Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the View Hierarchy button for All View", new string[] {
                "SmokeTest"}, SourceLine=80)]
        public virtual void CheckTheViewHierarchyButtonForAllView()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the View Hierarchy button for All View", null, new string[] {
                        "SmokeTest"});
#line 81
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 82
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 83
testRunner.Then("check the View Hierarchy button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for Employer channel", new string[] {
                "SmokeTest"}, SourceLine=85)]
        public virtual void CheckingTheDataForEmployerChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for Employer channel", null, new string[] {
                        "SmokeTest"});
#line 86
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 87
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 88
testRunner.When("view selected is Employer", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 89
testRunner.And("click on one Employer plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 90
testRunner.Then("Check the Header of Employer Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 91
testRunner.And("check the selected items in the particular Account of Employer Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for PBM channel", new string[] {
                "SmokeTest"}, SourceLine=94)]
        public virtual void CheckingTheDataForPBMChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for PBM channel", null, new string[] {
                        "SmokeTest"});
#line 95
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 96
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 97
testRunner.When("view selected is PBM", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 98
testRunner.And("click on one PBM plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 99
testRunner.Then("Check the Header of PBM Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 100
testRunner.And("check the selected items in the particular Account of PBM Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for Specialty Provider channel", new string[] {
                "SmokeTest"}, SourceLine=102)]
        public virtual void CheckingTheDataForSpecialtyProviderChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for Specialty Provider channel", null, new string[] {
                        "SmokeTest"});
#line 103
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 104
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 105
testRunner.When("view selected is Specialty Provider", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 106
testRunner.And("click on one Specialty Provider plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 107
testRunner.Then("Check the Header of Specialty Provider Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 108
testRunner.And("check the selected items in the particular Account of Specialty Provider Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for State Medicaid channel", new string[] {
                "SmokeTest"}, SourceLine=110)]
        public virtual void CheckingTheDataForStateMedicaidChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for State Medicaid channel", null, new string[] {
                        "SmokeTest"});
#line 111
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 112
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 113
testRunner.When("view selected is State Medicaid", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 114
testRunner.And("click on one State Medicaid plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 115
testRunner.Then("Check the Header of State Medicaid Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 116
testRunner.And("check the selected items in the particular Account of State Medicaid Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for Tricare channel", new string[] {
                "SmokeTest"}, SourceLine=118)]
        public virtual void CheckingTheDataForTricareChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for Tricare channel", null, new string[] {
                        "SmokeTest"});
#line 119
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 120
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 121
testRunner.When("view selected is Tricare", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 122
testRunner.And("click on one Tricare plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 123
testRunner.Then("Check the Header of Tricare Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 124
testRunner.And("check the selected items in the particular Account of Tricare Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for VA channel", new string[] {
                "SmokeTest"}, SourceLine=126)]
        public virtual void CheckingTheDataForVAChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for VA channel", null, new string[] {
                        "SmokeTest"});
#line 127
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 128
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 129
testRunner.When("view selected is VA", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 130
testRunner.And("click on one VA plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 131
testRunner.Then("Check the Header of VA Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 132
testRunner.And("check the selected items in the particular Account of VA Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for Medicare channel", new string[] {
                "SmokeTest"}, SourceLine=134)]
        public virtual void CheckingTheDataForMedicareChannel()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for Medicare channel", null, new string[] {
                        "SmokeTest"});
#line 135
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 136
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 137
testRunner.When("view selected is Medicare", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 138
testRunner.And("click on Medicare plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 139
testRunner.Then("Check the Header of Medicare Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 140
testRunner.And("check the selected items in the particular Account of Medicare Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for My Accounts", new string[] {
                "SmokeTest"}, SourceLine=142)]
        public virtual void CheckingTheDataForMyAccounts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for My Accounts", null, new string[] {
                        "SmokeTest"});
#line 143
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 144
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 145
testRunner.When("view selected is My Accounts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 146
testRunner.And("click on My Accounts plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 147
testRunner.Then("Check the Header of My Accounts Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 148
testRunner.And("check the selected items in the particular Account of My Accounts Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("checking the data for Parent Accounts", new string[] {
                "SmokeTest"}, SourceLine=151)]
        public virtual void CheckingTheDataForParentAccounts()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("checking the data for Parent Accounts", null, new string[] {
                        "SmokeTest"});
#line 152
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 153
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 154
testRunner.When("view selected is Parent Accounts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "When ");
#line 155
testRunner.And("click on Parent Accounts plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 156
testRunner.Then("Check the Header of Parent Accounts Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 157
testRunner.And("check the selected items in the particular Account of Parent Accounts Plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for Employer view in all the items", new string[] {
                "SmokeTest"}, SourceLine=160)]
        public virtual void CheckTheDataForEmployerViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for Employer view in all the items", null, new string[] {
                        "SmokeTest"});
#line 161
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 162
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 163
testRunner.Then("check the items for Employer View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for Medicare view in all the items", new string[] {
                "SmokeTest"}, SourceLine=165)]
        public virtual void CheckTheDataForMedicareViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for Medicare view in all the items", null, new string[] {
                        "SmokeTest"});
#line 166
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 167
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 168
testRunner.Then("Check whether the Account belong medicare view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 169
testRunner.Then("check the items for Medicare View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for Parent Accounts view in all the items", new string[] {
                "SmokeTest"}, SourceLine=171)]
        public virtual void CheckTheDataForParentAccountsViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for Parent Accounts view in all the items", null, new string[] {
                        "SmokeTest"});
#line 172
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 173
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 174
testRunner.Then("Check whether the Account belong Parent Accounts view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 175
testRunner.Then("check the items for Parent Accounts View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for My Accounts view in all the items", new string[] {
                "SmokeTest"}, SourceLine=177)]
        public virtual void CheckTheDataForMyAccountsViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for My Accounts view in all the items", null, new string[] {
                        "SmokeTest"});
#line 178
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 179
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 180
testRunner.Then("Check whether the Account belong My Accounts view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 181
testRunner.Then("check the items for My Accounts View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for PBM view in all the items", new string[] {
                "SmokeTest"}, SourceLine=184)]
        public virtual void CheckTheDataForPBMViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for PBM view in all the items", null, new string[] {
                        "SmokeTest"});
#line 185
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 186
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 187
testRunner.Then("Check whether the Account belong PBM view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 188
testRunner.Then("check the items for PBM View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for Specialty view in all the items", new string[] {
                "SmokeTest"}, SourceLine=190)]
        public virtual void CheckTheDataForSpecialtyViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for Specialty view in all the items", null, new string[] {
                        "SmokeTest"});
#line 191
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 192
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 193
testRunner.Then("Check whether the Account belong Specialty view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 194
testRunner.Then("check the items for Specialty View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for State Medicaid view in all the items", new string[] {
                "SmokeTest"}, SourceLine=196)]
        public virtual void CheckTheDataForStateMedicaidViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for State Medicaid view in all the items", null, new string[] {
                        "SmokeTest"});
#line 197
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 198
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 199
testRunner.Then("Check whether the Account belong State Medicaid view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 200
testRunner.Then("check the items for State Medicaid View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for Tricare view in all the items", new string[] {
                "SmokeTest"}, SourceLine=202)]
        public virtual void CheckTheDataForTricareViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for Tricare view in all the items", null, new string[] {
                        "SmokeTest"});
#line 203
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 204
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 205
testRunner.Then("Check whether the Account belong Tricare view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 206
testRunner.Then("check the items for Tricare View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the data for VA view in all the items", new string[] {
                "SmokeTest"}, SourceLine=208)]
        public virtual void CheckTheDataForVAViewInAllTheItems()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the data for VA view in all the items", null, new string[] {
                        "SmokeTest"});
#line 209
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 210
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 211
testRunner.Then("Check whether the Account belong VA view or not", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 212
testRunner.Then("check the items for VA View", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the buttons in My Accounts screen", new string[] {
                "SmokeTest"}, SourceLine=214)]
        public virtual void CheckTheButtonsInMyAccountsScreen()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the buttons in My Accounts screen", null, new string[] {
                        "SmokeTest"});
#line 215
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 216
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 217
testRunner.Then("click on next button and Previous button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 218
testRunner.And("click on each and every letter in the pagination", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Hover of elements in My Accounts Page", new string[] {
                "SmokeTest"}, SourceLine=220)]
        public virtual void CheckTheHoverOfElementsInMyAccountsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Hover of elements in My Accounts Page", null, new string[] {
                        "SmokeTest"});
#line 221
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 222
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 223
testRunner.Then("Select a view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 224
testRunner.And("check the hover functionality of the items", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 225
testRunner.Then("user clicks on my Accounts", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.ScenarioAttribute("Check the Account Plan of elements in My Accounts Page", new string[] {
                "SmokeTest"}, SourceLine=228)]
        public virtual void CheckTheAccountPlanOfElementsInMyAccountsPage()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Check the Account Plan of elements in My Accounts Page", null, new string[] {
                        "SmokeTest"});
#line 229
this.ScenarioInitialize(scenarioInfo);
            this.ScenarioStart();
#line 230
testRunner.Given("user is in Accounts Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 231
testRunner.Then("Select commercial view", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 232
testRunner.And("click on New Account Plan button", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 233
testRunner.And("Enter the mandatory fields and clicks on save", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line 234
testRunner.Then("Delete the created plan", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line 235
testRunner.And("close the My Accounts browser", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [TechTalk.SpecRun.TestRunCleanup()]
        public virtual void TestRunCleanup()
        {
            TechTalk.SpecFlow.TestRunnerManager.GetTestRunner().OnTestRunEnd();
        }
    }
}
#pragma warning restore
#endregion
